<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/Dataset_and_Dataloders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Create synthetic dataset
X,y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [5]:
# converting X,y into tensors
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype=torch.long)

In [7]:
from torch.utils.data import Dataset, DataLoader

In [8]:
class CustomDataset(Dataset):

  def __init__(self,features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [11]:
dataset = CustomDataset(X,y)

In [12]:
len(dataset)

10

In [17]:
dataset[3]

(tensor([-0.7206, -0.9606]), tensor(0))

In [19]:
dataloader= DataLoader(dataset, batch_size=2, shuffle=True)

In [23]:
for batch_feature, batch_label in dataloader:  # dataloader is iterable you can fetch data by applying loop only
  print(batch_feature)
  print(batch_label)
  print('-'*50)

tensor([[ 1.0683, -0.9701],
        [-0.9382, -0.5430]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-1.9629, -0.9923]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
