<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [20]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [21]:
# create dataset

features = torch.rand(10,5)
features

tensor([[0.7983, 0.6484, 0.6472, 0.0361, 0.1677],
        [0.3942, 0.3755, 0.0207, 0.5863, 0.7883],
        [0.6992, 0.0072, 0.0520, 0.0588, 0.0470],
        [0.2599, 0.9261, 0.9993, 0.2834, 0.0762],
        [0.4419, 0.5993, 0.1399, 0.3310, 0.5369],
        [0.9138, 0.8794, 0.0794, 0.4404, 0.6984],
        [0.4236, 0.8892, 0.5166, 0.9044, 0.4416],
        [0.9358, 0.3785, 0.3436, 0.9505, 0.5703],
        [0.6098, 0.8276, 0.1734, 0.9313, 0.9181],
        [0.1802, 0.9519, 0.3214, 0.5305, 0.8816]])

In [22]:
# create model / model object

model = Model(features.shape[1])

# call model for forward pass

model(features)


tensor([[0.4287],
        [0.4418],
        [0.4412],
        [0.4295],
        [0.4378],
        [0.4424],
        [0.4289],
        [0.4358],
        [0.4421],
        [0.4338]], grad_fn=<SigmoidBackward0>)

In [25]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1457, -0.1277,  0.3102]], requires_grad=True)

In [27]:
model.linear1.bias

Parameter containing:
tensor([ 0.0129, -0.0700, -0.2702], requires_grad=True)

In [11]:
!pip install torchinfo

In [28]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Now we use sequential model

In [38]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [39]:
features = torch.rand(10,3)

In [40]:
model = Model(features.shape[1])

model(features)

tensor([[0.5282],
        [0.5277],
        [0.5222],
        [0.5290],
        [0.5258],
        [0.5355],
        [0.5359],
        [0.5228],
        [0.5251],
        [0.5222]], grad_fn=<SigmoidBackward0>)