<a href="https://colab.research.google.com/github/harshs-data/Pytorch/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import torch.optim as optim

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [14]:
df.shape

(569, 33)

In [15]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [17]:
df.shape

(569, 31)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [19]:
df.describe()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500


In [20]:
df.isnull().sum()

,0
diagnosis,0
radius_mean,0
texture_mean,0
perimeter_mean,0
area_mean,0
smoothness_mean,0
compactness_mean,0
concavity_mean,0
concave points_mean,0
symmetry_mean,0


In [21]:
df.duplicated().sum()

np.int64(0)

### Train test split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2, random_state=42)

In [23]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

# scaling

In [24]:
scaler = StandardScaler()
df_train = scaler.fit_transform(X_train)
df_test = scaler.transform(X_test)

### LabelEncoder

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


### Numpy to pytorch tensors

In [26]:
X_train_tensor = torch.from_numpy(df_train.astype(np.float32))
X_test_tensor = torch.from_numpy(df_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [27]:
X_train_tensor.shape

torch.Size([455, 30])

### Creating batches

In [66]:
from torch.utils.data import Dataset, DataLoader

In [67]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [68]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [70]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Defining the Model

In [33]:
class MysimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

  '''
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss
    '''

Imp. parameters

In [48]:
learning_rate = 0.1
epochs = 25

In [49]:
# defining loss function
loss_function = nn.BCELoss()

### Training pipeline

In [50]:
# create model
model = MysimpleNN(X_train_tensor.shape[1])

In [51]:
# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

In [58]:
# define loop

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1)) # Reshape y_train_tensor

    # zero gradients
    '''
    for param in model.parameters():
      if param.grad is not None:
          param.grad.zero_()
    '''
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    '''
    with torch.no_grad():
      for param in model.parameters():
        param -= learning_rate * param.grad
    '''
    optimizer.step()

    # print loss in each epoch

    print(f'Epoch: {epoch+1}/{epochs}, Loss: {loss.item()}')



Epoch: 1/25, Loss: 0.0748746395111084
Epoch: 1/25, Loss: 0.07482954114675522
Epoch: 1/25, Loss: 0.07478459924459457
Epoch: 1/25, Loss: 0.07473984360694885
Epoch: 1/25, Loss: 0.07469525188207626
Epoch: 1/25, Loss: 0.0746508240699768
Epoch: 1/25, Loss: 0.07460658252239227
Epoch: 1/25, Loss: 0.07456249743700027
Epoch: 1/25, Loss: 0.074518583714962
Epoch: 1/25, Loss: 0.07447484135627747
Epoch: 1/25, Loss: 0.07443124800920486
Epoch: 1/25, Loss: 0.07438782602548599
Epoch: 1/25, Loss: 0.07434457540512085
Epoch: 1/25, Loss: 0.07430148124694824
Epoch: 1/25, Loss: 0.07425855100154877
Epoch: 2/25, Loss: 0.07421577721834183
Epoch: 2/25, Loss: 0.07417315244674683
Epoch: 2/25, Loss: 0.07413069158792496
Epoch: 2/25, Loss: 0.07408839464187622
Epoch: 2/25, Loss: 0.07404624670743942
Epoch: 2/25, Loss: 0.07400424778461456
Epoch: 2/25, Loss: 0.07396241277456284
Epoch: 2/25, Loss: 0.07392072677612305
Epoch: 2/25, Loss: 0.0738791897892952
Epoch: 2/25, Loss: 0.07383780926465988
Epoch: 2/25, Loss: 0.073796570

In [60]:
model.linear.weight

Parameter containing:
tensor([[ 0.4761,  0.6271,  0.5410,  0.4766,  0.1964, -0.1114,  0.7007,  0.7662,
          0.0024, -0.3192,  0.7293,  0.0091,  0.6564,  0.5497,  0.2015, -0.5203,
         -0.0574,  0.0824, -0.3884, -0.5074,  0.8655,  0.9151,  0.7170,  0.6561,
          0.5954,  0.2637,  0.5173,  0.6180,  0.8602,  0.1006]],
       requires_grad=True)

In [61]:
model.linear.bias

Parameter containing:
tensor([-0.5809], requires_grad=True)

In [62]:
y_pred

tensor([[2.9249e-02],
        [1.0000e+00],
        [1.0207e-05],
        [4.2879e-02],
        [9.1093e-05],
        [9.9980e-01],
        [6.0649e-04],
        [6.9241e-04],
        [5.7352e-03],
        [9.9985e-01],
        [7.0741e-02],
        [1.0000e+00],
        [9.9881e-01],
        [9.8055e-04],
        [2.5818e-03],
        [1.0000e+00],
        [1.0000e+00],
        [9.9999e-01],
        [1.1162e-02],
        [2.1873e-03],
        [2.1712e-02],
        [9.9126e-01],
        [2.4193e-01],
        [9.0136e-03],
        [2.2885e-01],
        [9.9665e-01],
        [2.8341e-03],
        [1.0000e+00],
        [5.5020e-05],
        [4.9925e-05],
        [9.8785e-01],
        [1.6490e-03],
        [9.9998e-01],
        [9.9999e-01],
        [6.8067e-01],
        [4.7850e-04],
        [8.9329e-01],
        [1.9912e-04],
        [1.4383e-05],
        [3.7856e-02],
        [1.5369e-03],
        [1.0000e+00],
        [9.9991e-01],
        [5.4570e-05],
        [1.4657e-02],
        [2

# Evaluation


In [72]:
'''
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')
'''

# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9688


In [73]:

y_pred

tensor([[1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])